### ISSUE TITLE
[v0.3.0] Cannot import `@hocs/debounce-handler` using browserify

### ISSUE THREAD

**Issue by subuta** [deepsweet/hocs#12]
It looks like recent package.json change(adding `browser` field) breaks module import via browserify.

https://github.com/deepsweet/hocs/commit/e56d2738d149bc8eaf389edc109c82e60ea81484#diff-fa58850984d1284fe1035e891a0d5b50

```
# not works...
import debounceHandler from '@hocs/debounce-handler'
```

When i specify import path like this(using `main` setting in package.json), import works correctly.

```
# works!
import debounceHandler from '@hocs/debounce-handler/build/node-cjs'
```

### Error

```
SyntaxError: 'import' and 'export' may only appear at the top level (14:0) while parsing /Users/subuta/repo/xxxxx/node_modules/@hocs/debounce-handler/build/browser-esm/index.js while parsing file: /Users/subuta/repo/xxxxx/node_modules/@hocs/debounce-handler/build/browser-esm/index.js
```

#### Package version

- `watchify@3.9.0`
- `babelify@7.3.0`

#### .babelrc

```
{
  "presets": [
    "es2015",
    "stage-2",
    "react"
  ]
}
```

**Comment by deepsweet** [comment]
hi.

yeah, that's why I've bumped minor version while major is zero – this could mean breaking change as well as a new feature. bundler with ES Modules support is required (usually comes as ["Tree Shaking"](https://webpack.js.org/guides/tree-shaking/) feature in bundlers like Webpack or Rollup) – I should have mentioned this in release changelog more explicitly, sorry.

I see few options:
1. continue using v0.2
2. switch to Webpack or Rollup
3. try [rollupify](https://github.com/nolanlawson/rollupify)

looking forward for your reply, I think that 3 is a good way to go if you want to continue using Browserify. ESM (ES Modules) is the future for sure, I just decided to force it a bit by providing build with untranspiled imports/exports.

**Comment by subuta** [comment]
@deepsweet Thanks for reply!

> 1. continue using v0.2

We just bumped up `recompose` version to latest and that won't work with v0.2(because of `createEagerFactory` changes)

> 2. switch to Webpack or Rollup

I prefer browserify for use of use than webpack sorry ;)

I just tried 3 and can't make it work, sadly. We need to make our repository compatible with rollup configuration first and it looks little bit tough(and we didn't have enough time to try that currently ...)

We will re-try browserify + rollupify setup later and will report progress to here :)

**Comment by deepsweet** [comment]
>We will re-try browserify + rollupify setup later and will report progress to here :)

any news? :)

**Comment by subuta** [comment]
@deepsweet I created new repository to test `browserify + rollupify` setup and it works now! thanks for your advise :)

What I did was make rollup transpiles `@hocs/debounce-handler` by specifying exclude option correctly at `rollup.config.js`

```js
babel({
    exclude: [
      '!node_modules/@hocs',
      'node_modules/**'
    ]
})
```
and build it using browserify 

```shell
browserify webapp/index.js -t [ rollupify --config rollup.config.js ] > ./public/bundle.js"
```

Full example is in https://github.com/subuta/play-with-browserify-and-rollupify

**Comment by deepsweet** [comment]
:pray:
