### ISSUE TITLE
Technique for adding event listeners when using with-lifecycle?

### ISSUE THREAD

**Issue by GollyJer** [deepsweet/hocs#17]
Hi @deepsweet.

Just wondering your pattern for adding event listeners when using *with-lifecycle*.
ie - How do you add event listeners without access to `this`?

**Comment by deepsweet** [comment]
Hi.

Lifecycle HOC is designed to work in 2 modes, with methods object and as a factory, just like `withHandlers`. So if you pass a function to `withLifecycle` instead of an object you'll get a scope from which you should return methods object. It's invoked from a component class constructor only once and you can store whatever in that function scope including event handlers.


```js
withLifecycle((props) => {
  const onEvent = () => {}

  return {
    onDidMount() {
      global.addEventListener('event', onEvent)
    },
    onWillUnmount() {
      global.removeEventListener('event', onEvent)
    }
  }
})
```

**Comment by GollyJer** [comment]
Awesome... thanks!
