### ISSUE TITLE
getDerivedStateFromProps

### ISSUE THREAD

**Issue by yyynnn** [deepsweet/hocs#20]
Hi! Cool HOC collection!

Could you please provide a usage example of a getDerivedStateFromProps method?
Is it just work inside onReceiveProps but with new logic?

**Comment by deepsweet** [comment]
>Hi. Cool HOC collection!

Hi. Thanks :)

>Is it just work inside onReceiveProps but with new logic?

Exactly.

Because `getDerivedStateFromProps` with its returned state doesn't match well the HOCs idea, `onReceiveProps` lifecycle method is basically a `getDerivedStateFromProps` under the hood but only as a callback, without the returned state feature.

I hope that `onReceiveProps` name is not very confusing, I had to improvise.

**Comment by deepsweet** [comment]
```js
withLifecycle({
  onReceiveProps(props, nextProps) {
    // called every time `getDerivedStateFromProps` is called,
    // i.e. "on constructor" as well
  }
})
```

**Comment by yyynnn** [comment]
Noice! My life's getting easier.
It would be nice to see some basic examples in the docs for each of the methods though - better help newcomers. Maybe i'll fetch a PR.

**Comment by deepsweet** [comment]
>Maybe i'll fetch a PR

Please do 🙏
